#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaTecnologica
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="estandares")]
	public partial class basezonaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public basezonaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["estandaresConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vusuario> Vusuarios
		{
			get
			{
				return this.GetTable<Vusuario>();
			}
		}
		
		public System.Data.Linq.Table<Vcompra> Vcompras
		{
			get
			{
				return this.GetTable<Vcompra>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_validar_usuario")]
		public ISingleResult<sp_validar_usuarioResult> sp_validar_usuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, password, rol);
			return ((ISingleResult<sp_validar_usuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarUsuario")]
		public ISingleResult<SP_EliminarUsuarioResult> SP_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(15)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, usuario);
			return ((ISingleResult<SP_EliminarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Vroles")]
		public ISingleResult<VrolesResult> Vroles()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<VrolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarUsuario")]
		public ISingleResult<SP_BuscarUsuarioResult> SP_BuscarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<SP_BuscarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarUsuario")]
		public ISingleResult<SP_AgregarUsuarioResult> SP_AgregarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Login", DbType="VarChar(15)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(15)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Foto", DbType="Image")] System.Data.Linq.Binary foto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, correo, primerNombre, segundoNombre, primerApellido, segundoApellido, idRol, usuario, foto);
			return ((ISingleResult<SP_AgregarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarUsuario")]
		public ISingleResult<SP_ModificarUsuarioResult> SP_ModificarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Login", DbType="VarChar(15)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_vigencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> trylogin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Foto", DbType="Image")] System.Data.Linq.Binary foto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(15)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, login, correo, primerNombre, segundoNombre, primerApellido, segundoApellido, fecha_vigencia, trylogin, foto, idRol, usuario);
			return ((ISingleResult<SP_ModificarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarCompra")]
		public ISingleResult<SP_EliminarCompraResult> SP_EliminarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_compra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_compra, usuario);
			return ((ISingleResult<SP_EliminarCompraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vProductos")]
		public ISingleResult<vProductosResult> vProductos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<vProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vProveedores")]
		public ISingleResult<vProveedoresResult> vProveedores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<vProveedoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarCompra")]
		public ISingleResult<SP_AgregarCompraResult> SP_AgregarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precio_u, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_producto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_proveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cantidad, precio_u, id_producto, id_proveedor, usuario);
			return ((ISingleResult<SP_AgregarCompraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarCompra")]
		public ISingleResult<SP_ModificarCompraResult> SP_ModificarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_compra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precio_u, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_producto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_proveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string usuarioActualiza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_compra, cantidad, precio_u, fecha, id_producto, id_proveedor, estado, usuarioActualiza);
			return ((ISingleResult<SP_ModificarCompraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarCompra")]
		public ISingleResult<SP_BuscarCompraResult> SP_BuscarCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_compra)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_compra);
			return ((ISingleResult<SP_BuscarCompraResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vusuarios")]
	public partial class Vusuario
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _correo;
		
		private string _primer_nombre;
		
		private string _segundo_nombre;
		
		private string _primer_apellido;
		
		private string _segundo_apellido;
		
		private string _Nombre;
		
		private System.DateTime _vigencia_password;
		
		private System.Nullable<int> _trylogin;
		
		private System.Data.Linq.Binary _foto;
		
		private int _id_rol;
		
		private string _rol;
		
		private string _UsuarioActualiza;
		
		private System.DateTime _FechaActualiza;
		
		public Vusuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_nombre
		{
			get
			{
				return this._primer_nombre;
			}
			set
			{
				if ((this._primer_nombre != value))
				{
					this._primer_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_nombre
		{
			get
			{
				return this._segundo_nombre;
			}
			set
			{
				if ((this._segundo_nombre != value))
				{
					this._segundo_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_apellido
		{
			get
			{
				return this._primer_apellido;
			}
			set
			{
				if ((this._primer_apellido != value))
				{
					this._primer_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_apellido
		{
			get
			{
				return this._segundo_apellido;
			}
			set
			{
				if ((this._segundo_apellido != value))
				{
					this._segundo_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(61) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigencia_password", DbType="Date NOT NULL")]
		public System.DateTime vigencia_password
		{
			get
			{
				return this._vigencia_password;
			}
			set
			{
				if ((this._vigencia_password != value))
				{
					this._vigencia_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trylogin", DbType="Int")]
		public System.Nullable<int> trylogin
		{
			get
			{
				return this._trylogin;
			}
			set
			{
				if ((this._trylogin != value))
				{
					this._trylogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this._id_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualiza", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UsuarioActualiza
		{
			get
			{
				return this._UsuarioActualiza;
			}
			set
			{
				if ((this._UsuarioActualiza != value))
				{
					this._UsuarioActualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualiza", DbType="DateTime NOT NULL")]
		public System.DateTime FechaActualiza
		{
			get
			{
				return this._FechaActualiza;
			}
			set
			{
				if ((this._FechaActualiza != value))
				{
					this._FechaActualiza = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vcompras")]
	public partial class Vcompra
	{
		
		private int _id_compra;
		
		private int _id_producto;
		
		private string _producto;
		
		private int _cantidad;
		
		private decimal _precio_unitario;
		
		private decimal _total;
		
		private string _usuario;
		
		private int _id_proveedor;
		
		private string _nombre_proveedor;
		
		private System.DateTime _fecha_inserta;
		
		public Vcompra()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", DbType="Int NOT NULL")]
		public int id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					this._id_compra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this._id_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					this._producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[precio unitario]", Storage="_precio_unitario", DbType="Money NOT NULL")]
		public decimal precio_unitario
		{
			get
			{
				return this._precio_unitario;
			}
			set
			{
				if ((this._precio_unitario != value))
				{
					this._precio_unitario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", DbType="Int NOT NULL")]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					this._id_proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[nombre proveedor]", Storage="_nombre_proveedor", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string nombre_proveedor
		{
			get
			{
				return this._nombre_proveedor;
			}
			set
			{
				if ((this._nombre_proveedor != value))
				{
					this._nombre_proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fecha inserta]", Storage="_fecha_inserta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_inserta
		{
			get
			{
				return this._fecha_inserta;
			}
			set
			{
				if ((this._fecha_inserta != value))
				{
					this._fecha_inserta = value;
				}
			}
		}
	}
	
	public partial class sp_validar_usuarioResult
	{
		
		private int _id_usuario;
		
		private int _cod;
		
		private string _correo;
		
		private string _mensaje;
		
		public sp_validar_usuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this._id_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarUsuarioResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_EliminarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class VrolesResult
	{
		
		private int _id_rol;
		
		private string _rol;
		
		public VrolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this._id_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarUsuarioResult
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _correo;
		
		private string _primer_nombre;
		
		private string _segundo_nombre;
		
		private string _primer_apellido;
		
		private string _segundo_apellido;
		
		private string _Nombre;
		
		private System.DateTime _vigencia_password;
		
		private System.Nullable<int> _trylogin;
		
		private System.Data.Linq.Binary _foto;
		
		private int _id_rol;
		
		private string _Rol;
		
		private string _usuarioInserta;
		
		private System.DateTime _fechaInserta;
		
		private string _usuarioActualiza;
		
		private System.Nullable<System.DateTime> _fechaActualiza;
		
		public SP_BuscarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_nombre
		{
			get
			{
				return this._primer_nombre;
			}
			set
			{
				if ((this._primer_nombre != value))
				{
					this._primer_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_nombre
		{
			get
			{
				return this._segundo_nombre;
			}
			set
			{
				if ((this._segundo_nombre != value))
				{
					this._segundo_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_apellido
		{
			get
			{
				return this._primer_apellido;
			}
			set
			{
				if ((this._primer_apellido != value))
				{
					this._primer_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_apellido
		{
			get
			{
				return this._segundo_apellido;
			}
			set
			{
				if ((this._segundo_apellido != value))
				{
					this._segundo_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(61) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigencia_password", DbType="Date NOT NULL")]
		public System.DateTime vigencia_password
		{
			get
			{
				return this._vigencia_password;
			}
			set
			{
				if ((this._vigencia_password != value))
				{
					this._vigencia_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trylogin", DbType="Int")]
		public System.Nullable<int> trylogin
		{
			get
			{
				return this._trylogin;
			}
			set
			{
				if ((this._trylogin != value))
				{
					this._trylogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this._id_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioInserta", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuarioInserta
		{
			get
			{
				return this._usuarioInserta;
			}
			set
			{
				if ((this._usuarioInserta != value))
				{
					this._usuarioInserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInserta", DbType="DateTime NOT NULL")]
		public System.DateTime fechaInserta
		{
			get
			{
				return this._fechaInserta;
			}
			set
			{
				if ((this._fechaInserta != value))
				{
					this._fechaInserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioActualiza", DbType="VarChar(15)")]
		public string usuarioActualiza
		{
			get
			{
				return this._usuarioActualiza;
			}
			set
			{
				if ((this._usuarioActualiza != value))
				{
					this._usuarioActualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaActualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaActualiza
		{
			get
			{
				return this._fechaActualiza;
			}
			set
			{
				if ((this._fechaActualiza != value))
				{
					this._fechaActualiza = value;
				}
			}
		}
	}
	
	public partial class SP_AgregarUsuarioResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_AgregarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(27) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificarUsuarioResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_ModificarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarCompraResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_EliminarCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class vProductosResult
	{
		
		private int _id_producto;
		
		private string _nombre_producto;
		
		public vProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this._id_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_producto", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string nombre_producto
		{
			get
			{
				return this._nombre_producto;
			}
			set
			{
				if ((this._nombre_producto != value))
				{
					this._nombre_producto = value;
				}
			}
		}
	}
	
	public partial class vProveedoresResult
	{
		
		private int _id_proveedor;
		
		private string _nombre_proveedor;
		
		public vProveedoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", DbType="Int NOT NULL")]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					this._id_proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_proveedor", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string nombre_proveedor
		{
			get
			{
				return this._nombre_proveedor;
			}
			set
			{
				if ((this._nombre_proveedor != value))
				{
					this._nombre_proveedor = value;
				}
			}
		}
	}
	
	public partial class SP_AgregarCompraResult
	{
		
		private System.Nullable<int> _id;
		
		private string _mensaje;
		
		public SP_AgregarCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(26) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificarCompraResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_ModificarCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarCompraResult
	{
		
		private int _id_compra;
		
		private int _id_producto;
		
		private string _producto;
		
		private int _cantidad;
		
		private decimal _precioUnitario;
		
		private decimal _total;
		
		private string _usuario;
		
		private int _id_proveedor;
		
		private string _nombreProveedor;
		
		private System.DateTime _fechaInserta;
		
		private string _estado;
		
		public SP_BuscarCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", DbType="Int NOT NULL")]
		public int id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					this._id_compra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this._id_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					this._producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioUnitario", DbType="Money NOT NULL")]
		public decimal precioUnitario
		{
			get
			{
				return this._precioUnitario;
			}
			set
			{
				if ((this._precioUnitario != value))
				{
					this._precioUnitario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", DbType="Int NOT NULL")]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					this._id_proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProveedor", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string nombreProveedor
		{
			get
			{
				return this._nombreProveedor;
			}
			set
			{
				if ((this._nombreProveedor != value))
				{
					this._nombreProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInserta", DbType="DateTime NOT NULL")]
		public System.DateTime fechaInserta
		{
			get
			{
				return this._fechaInserta;
			}
			set
			{
				if ((this._fechaInserta != value))
				{
					this._fechaInserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(30)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
