#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonaTecnologica
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="estandares")]
	public partial class basezonaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public basezonaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["estandaresConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basezonaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vusuario> Vusuarios
		{
			get
			{
				return this.GetTable<Vusuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_validar_usuario")]
		public ISingleResult<sp_validar_usuarioResult> sp_validar_usuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, password, rol);
			return ((ISingleResult<sp_validar_usuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarUsuario")]
		public ISingleResult<SP_EliminarUsuarioResult> SP_EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(15)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, usuario);
			return ((ISingleResult<SP_EliminarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Vroles")]
		public ISingleResult<VrolesResult> Vroles()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<VrolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarUsuario")]
		public ISingleResult<SP_BuscarUsuarioResult> SP_BuscarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<SP_BuscarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarUsuario")]
		public ISingleResult<SP_AgregarUsuarioResult> SP_AgregarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Login", DbType="VarChar(15)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(15)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Foto", DbType="Image")] System.Data.Linq.Binary foto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), login, correo, primerNombre, segundoNombre, primerApellido, segundoApellido, idRol, usuario, foto);
			return ((ISingleResult<SP_AgregarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarUsuario")]
		public ISingleResult<SP_ModificarUsuarioResult> SP_ModificarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Login", DbType="VarChar(15)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_vigencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> trylogin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Foto", DbType="Image")] System.Data.Linq.Binary foto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(15)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, login, correo, primerNombre, segundoNombre, primerApellido, segundoApellido, fecha_vigencia, trylogin, foto, idRol, usuario);
			return ((ISingleResult<SP_ModificarUsuarioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vusuarios")]
	public partial class Vusuario
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _correo;
		
		private string _primer_nombre;
		
		private string _segundo_nombre;
		
		private string _primer_apellido;
		
		private string _segundo_apellido;
		
		private string _Nombre;
		
		private System.DateTime _vigencia_password;
		
		private System.Nullable<int> _trylogin;
		
		private System.Data.Linq.Binary _foto;
		
		private int _id_rol;
		
		private string _rol;
		
		private string _UsuarioActualiza;
		
		private System.DateTime _FechaActualiza;
		
		public Vusuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_nombre
		{
			get
			{
				return this._primer_nombre;
			}
			set
			{
				if ((this._primer_nombre != value))
				{
					this._primer_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_nombre
		{
			get
			{
				return this._segundo_nombre;
			}
			set
			{
				if ((this._segundo_nombre != value))
				{
					this._segundo_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_apellido
		{
			get
			{
				return this._primer_apellido;
			}
			set
			{
				if ((this._primer_apellido != value))
				{
					this._primer_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_apellido
		{
			get
			{
				return this._segundo_apellido;
			}
			set
			{
				if ((this._segundo_apellido != value))
				{
					this._segundo_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(61) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigencia_password", DbType="Date NOT NULL")]
		public System.DateTime vigencia_password
		{
			get
			{
				return this._vigencia_password;
			}
			set
			{
				if ((this._vigencia_password != value))
				{
					this._vigencia_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trylogin", DbType="Int")]
		public System.Nullable<int> trylogin
		{
			get
			{
				return this._trylogin;
			}
			set
			{
				if ((this._trylogin != value))
				{
					this._trylogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this._id_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualiza", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UsuarioActualiza
		{
			get
			{
				return this._UsuarioActualiza;
			}
			set
			{
				if ((this._UsuarioActualiza != value))
				{
					this._UsuarioActualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualiza", DbType="DateTime NOT NULL")]
		public System.DateTime FechaActualiza
		{
			get
			{
				return this._FechaActualiza;
			}
			set
			{
				if ((this._FechaActualiza != value))
				{
					this._FechaActualiza = value;
				}
			}
		}
	}
	
	public partial class sp_validar_usuarioResult
	{
		
		private int _id_usuario;
		
		private int _cod;
		
		private string _correo;
		
		private string _mensaje;
		
		public sp_validar_usuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this._id_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_EliminarUsuarioResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_EliminarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class VrolesResult
	{
		
		private int _id_rol;
		
		private string _rol;
		
		public VrolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this._id_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarUsuarioResult
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _correo;
		
		private string _primer_nombre;
		
		private string _segundo_nombre;
		
		private string _primer_apellido;
		
		private string _segundo_apellido;
		
		private string _Nombre;
		
		private System.DateTime _vigencia_password;
		
		private System.Nullable<int> _trylogin;
		
		private System.Data.Linq.Binary _foto;
		
		private int _id_rol;
		
		private string _Rol;
		
		private string _usuarioInserta;
		
		private System.DateTime _fechaInserta;
		
		private string _usuarioActualiza;
		
		private System.Nullable<System.DateTime> _fechaActualiza;
		
		public SP_BuscarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_nombre
		{
			get
			{
				return this._primer_nombre;
			}
			set
			{
				if ((this._primer_nombre != value))
				{
					this._primer_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_nombre
		{
			get
			{
				return this._segundo_nombre;
			}
			set
			{
				if ((this._segundo_nombre != value))
				{
					this._segundo_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string primer_apellido
		{
			get
			{
				return this._primer_apellido;
			}
			set
			{
				if ((this._primer_apellido != value))
				{
					this._primer_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segundo_apellido
		{
			get
			{
				return this._segundo_apellido;
			}
			set
			{
				if ((this._segundo_apellido != value))
				{
					this._segundo_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(61) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigencia_password", DbType="Date NOT NULL")]
		public System.DateTime vigencia_password
		{
			get
			{
				return this._vigencia_password;
			}
			set
			{
				if ((this._vigencia_password != value))
				{
					this._vigencia_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trylogin", DbType="Int")]
		public System.Nullable<int> trylogin
		{
			get
			{
				return this._trylogin;
			}
			set
			{
				if ((this._trylogin != value))
				{
					this._trylogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this._id_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioInserta", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuarioInserta
		{
			get
			{
				return this._usuarioInserta;
			}
			set
			{
				if ((this._usuarioInserta != value))
				{
					this._usuarioInserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInserta", DbType="DateTime NOT NULL")]
		public System.DateTime fechaInserta
		{
			get
			{
				return this._fechaInserta;
			}
			set
			{
				if ((this._fechaInserta != value))
				{
					this._fechaInserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioActualiza", DbType="VarChar(15)")]
		public string usuarioActualiza
		{
			get
			{
				return this._usuarioActualiza;
			}
			set
			{
				if ((this._usuarioActualiza != value))
				{
					this._usuarioActualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaActualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaActualiza
		{
			get
			{
				return this._fechaActualiza;
			}
			set
			{
				if ((this._fechaActualiza != value))
				{
					this._fechaActualiza = value;
				}
			}
		}
	}
	
	public partial class SP_AgregarUsuarioResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_AgregarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(27) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificarUsuarioResult
	{
		
		private System.Nullable<int> _codigo;
		
		private string _mensaje;
		
		public SP_ModificarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string mensaje
		{
			get
			{
				return this._mensaje;
			}
			set
			{
				if ((this._mensaje != value))
				{
					this._mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
